### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by skyejy** [SMILELab-FL/FedLab-benchmarks#19]
Hello， 
Thanks for reading~

I follow the tutorial from ：https://github.com/SMILELab-FL/FedLab-benchmarks/blob/master/fedlab_benchmarks/datasets/fmnist/fmnist_tutorial.ipynb

However, the following error exists:
**FileNotFoundError: [Errno 2] No such file or directory: '../partition-reports/fmnist_noniid-label_1_clients_10.csv'**

How can I fix it? Please.

**Comment by Zengdun-cs** [comment]
Issue received.
My teammate will answer you later.

**Comment by AgentDS** [comment]
Hi, we actually upload this file onto repo. Please check [here](https://github.com/SMILELab-FL/FedLab-benchmarks/tree/master/fedlab_benchmarks/datasets/partition-reports). This file (`fmnist_noniid-label_1_clients_10.csv`) is created by function `partition_report`(details of this function, check [here](https://github.com/SMILELab-FL/FedLab/blob/3d1375678fb7db3f3e93babcbba9f1f03590ede2/fedlab/utils/functional.py#L132)).

Please feel free to contact us if you still have problem.

Best

**Comment by skyejy** [comment]
> Hi, we actually upload this file onto repo. Please check [here](https://github.com/SMILELab-FL/FedLab-benchmarks/tree/master/fedlab_benchmarks/datasets/partition-reports). This file (`fmnist_noniid-label_1_clients_10.csv`) is created by function `partition_report`(details of this function, check [here](https://github.com/SMILELab-FL/FedLab/blob/3d1375678fb7db3f3e93babcbba9f1f03590ede2/fedlab/utils/functional.py#L132)).
> 
> You can also create a folder named as `partition-reports` in directory `fedlab_benchmarks/datasets/` if you don't want to download other files in `fedlab_benchmarks`. Then function `partition_report` will generate `fmnist_noniid-label_1_clients_10.csv` in this folder.
> 
> I guess you might need basic knowledge about Linux file path ([this](https://www.runoob.com/linux/linux-file-content-manage.html) might help you). File path used in our code is for Linux/macOS system. If you use windows system, please check [this](https://libertydream.github.io/2019/08/10/Python-3%E5%B0%8F%E6%8A%80%E5%B7%A7-%E4%BE%BF%E6%8D%B7%E5%A4%84%E7%90%86Windows-Mac%E5%92%8CLinux%E4%B8%8A%E7%9A%84%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84/), [this](https://www.delftstack.com/zh/howto/python/relative-path-in-python/) and [this](http://c.biancheng.net/view/5693.html).
> 
> Please feel free to contact us if you still have problem.
> 
> Best

Thank you very much for prompt reply and detailed answer.  I will have a try.

Regards,
