### ISSUE TITLE
Errors in the current version

### ISSUE THREAD

**Issue by Zmjcc** [SMILELab-FL/FedLab-benchmarks#21]
When I try to run the demo, there seems that some files are lost, like the following
ModuleNotFoundError: No module named 'leaf.read_util'.

Moreover, It is suggested that your example on LEAF can be completed in a folder instead of using ''...'' other ways to call the files under the parent folder, it makes the program look messy and prone to the following errors:
ValueError: attempted relative import beyond top-level package

Anyway, this is a nice work for the federated learning experiment. I hope it can be improved.

**Comment by Zengdun-cs** [comment]
Thanks for your bug report.  
Could you please tell us which python script triggered the bug. So we can fix it.

**Comment by Zmjcc** [comment]
In the Leaf/nlp_utils/dataset_vocab/sample_build_vocab.py, there is a call "from ...read_util import get_data_json", while in the Leaf folder, there is not such a file, but I have found it in your former version. 
There is a small suggestion that you can provide a more completed training example. The training process can be completed in the current version, but there is no record of relevant training indicators, i.e., the test accuracy or training loss.
