### ISSUE TITLE
运行 fedavg/LEAF_test.sh 报错

### ISSUE THREAD

**Issue by KarhouTam** [SMILELab-FL/FedLab-benchmarks#23]
报错显示找不到需要的 .pkl 文件。 会不会是在之前的整合目录时没有修改这里。 （我已经在 `fedlab_benchmarks/datasets/` 的 `/femnist` 和 `/shakespeare` 目录中运行过你们的 README 文档中的 preprocess.sh 示例）

**Comment by Starry-Hu** [comment]
KarhouTam你好，请问你现在运行的是哪个版本？pkl文件需要在`[fedlab_benchmarks/leaf/gen_pickle_dataset.sh](https://github.com/SMILELab-FL/FedLab-benchmarks/blob/master/fedlab_benchmarks/leaf/gen_pickle_dataset.sh)` 中运行生成相应的pkl文件。`fedlab_benchmarks/datasets/`是用于leaf原始数据下载，数据集对应pickle文件的生成是用于加速运行时的数据加载。
感谢你的提问，请尝试`gen_pickle_dataset.sh`生成对应的pickle文件，如果还有问题请再询问我们。

**Comment by KarhouTam** [comment]
感谢解惑。

**Comment by L-ien** [comment]
我也遇到了相同的问题，在运行 `preprocess.sh` 后，该数据集目录下生成的data目录中，除了/raw_data文件夹外，其他目录下均为空，导致后续运行`bash gen_pickle_dataset.sh "femnist" "../datasets/femnist/data" "./pickle_datasets"`报错，请问可能是哪里出了问题？
![微信图片_20220617104141](https://user-images.githubusercontent.com/66815471/174214261-18cb638b-ac24-40d0-80d2-bd6e5a22803c.png)

**Comment by Starry-Hu** [comment]
> 我也遇到了相同的问题，在运行 `preprocess.sh` 后，该数据集目录下生成的data目录中，除了/raw_data文件夹外，其他目录下均为空，导致后续运行`bash gen_pickle_dataset.sh "femnist" "../datasets/femnist/data" "./pickle_datasets"`报错，请问可能是哪里出了问题？ ![微信图片_20220617104141](https://user-images.githubusercontent.com/66815471/174214261-18cb638b-ac24-40d0-80d2-bd6e5a22803c.png)

哈喽，麻烦你提供一下完整的preprocess.sh的运行脚本，以及拉取目前FedLab-benchmarks的最新版本后再试一下，请提供详细的处理信息方便我们解答

**Comment by KarhouTam** [comment]
Hi, L-ien. 或许你可以尝试一下我的 readme里 Dataset 中的那条命令来预处理 femnist.



---Original---
From: ***@***.***&gt;
Sent at: 2022年6月17日(Fri) AM10:44
To: ***@***.***&gt;;
Cc: "Jiahao ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [SMILELab-FL/FedLab-benchmarks] 运行 fedavg/LEAF_test.sh 报错 (Issue #23)




 
我也遇到了相同的问题，在运行 preprocess.sh 后，该数据集目录下生成的data目录中，除了/raw_data文件夹外，其他目录下均为空，导致后续运行bash gen_pickle_dataset.sh "femnist" "../datasets/femnist/data" "./pickle_datasets"报错，请问可能是哪里出了问题？

**Comment by L-ien** [comment]
> 
> 哈喽，麻烦你提供一下完整的preprocess.sh的运行脚本，以及拉取目前FedLab-benchmarks的最新版本后再试一下，请提供详细的处理信息方便我们解答

你好，我在用最新版本运行后，仍然是同样的问题，我的fedlab版本为1.1.2，用git bash执行预处理指令为 `preprocess.sh-s niid --sf 0.05 -k 0 -t sample` ，运行脚本都是今天拉取的，与当前最新版本一致，文件已如下附上
[preprocess.zip](https://github.com/SMILELab-FL/FedLab-benchmarks/files/8925287/preprocess.zip)

**Comment by Starry-Hu** [comment]
> > 哈喽，麻烦你提供一下完整的preprocess.sh的运行脚本，以及拉取目前FedLab-benchmarks的最新版本后再试一下，请提供详细的处理信息方便我们解答
> 
> 你好，我在用最新版本运行后，仍然是同样的问题，我的fedlab版本为1.1.2，用git bash执行预处理指令为 `preprocess.sh-s niid --sf 0.05 -k 0 -t sample` ，运行脚本都是今天拉取的，与当前最新版本一致，文件已如下附上 [preprocess.zip](https://github.com/SMILELab-FL/FedLab-benchmarks/files/8925287/preprocess.zip)

可以给我看一下你运行preprocess.sh脚本的输出情况吗

**Comment by L-ien** [comment]
> > > 哈喽，麻烦你提供一下完整的preprocess.sh的运行脚本，以及拉取目前FedLab-benchmarks的最新版本后再试一下，请提供详细的处理信息方便我们解答
> > 
> > 
> > 你好，我在用最新版本运行后，仍然是同样的问题，我的fedlab版本为1.1.2，用git bash执行预处理指令为 `preprocess.sh-s niid --sf 0.05 -k 0 -t sample` ，运行脚本都是今天拉取的，与当前最新版本一致，文件已如下附上 [preprocess.zip](https://github.com/SMILELab-FL/FedLab-benchmarks/files/8925287/preprocess.zip)
> 
> 可以给我看一下你运行preprocess.sh脚本的输出情况吗

![微信图片_20220617154205](https://user-images.githubusercontent.com/66815471/174250580-902e9658-475e-4c0c-a32e-0e2a3d94571a.png)


这是运行结果
