### ISSUE TITLE
运行fedasync/cross_process demo出错

### ISSUE THREAD

**Issue by kid1999** [SMILELab-FL/FedLab-benchmarks#29]
在执行跨进程的异步FL任务时会陷入等待。
```
hm@hm-IdeaCentre-GeekPro-15ICK:~/test/fedasync$ bash quick_start.sh 
torch.distributed connection is initializing with ip address 127.0.0.1:3002, rank 0, world size: 3, backend gloo, ethernet None.
torch.distributed connection is initializing with ip address 127.0.0.1:3002, rank 1, world size: 3, backend gloo, ethernet None.
torch.distributed connection is initializing with ip address 127.0.0.1:3002, rank 2, world size: 3, backend gloo, ethernet None.
2022-04-07 22:13:36,811 - root - INFO - Added key: store_based_barrier_key:1 to store for rank: 1
2022-04-07 22:13:36,811 - root - INFO - Added key: store_based_barrier_key:1 to store for rank: 0
2022-04-07 22:13:36,811 - root - INFO - Added key: store_based_barrier_key:1 to store for rank: 2
2022-04-07 22:13:36,812 - client 1 - INFO - request parameter procedure
2022-04-07 22:13:36,812 - client 2 - INFO - request parameter procedure
```

**Comment by kid1999** [comment]
测试发现`ServerManager`在初始化接收client信息，调用`fedlab/core/communicator/processor`中`recv_content`函数接收client发来的信息会异常退出？

**Comment by AgentDS** [comment]
你好请问用的是哪个版本的fedlab

**Comment by kid1999** [comment]
谢谢！
我刚才又检查了一下版本1.1.4是不行的，server在解包的时候scices = [1] 导致解包失败退出。
但是我刚才切换到1.1.2版本这个问题就消失了。希望后续修复这个bug。
谢谢解惑！

发件人: Siqi ***@***.***>
发送时间: 2022年4月9日 11:26
收件人: ***@***.***>
抄送: hell ***@***.***>; ***@***.***>
主题: Re: [SMILELab-FL/FedLab-benchmarks] 运行fedasync/cross_process demo出错 (Issue #29)


你好请问用的是哪个版本的fedlab

―

**Comment by AgentDS** [comment]
好的我们会试图修复，谢谢

**Comment by Zengdun-cs** [comment]
Bug已修复，卸载旧版本。
pip install fedlab 安装v1.1.5版本即可。

**Comment by Zengdun-cs** [comment]
感谢bug反馈，欢迎一起改进FedLab。

**Comment by kid1999** [comment]
你好，我发现ServerAsynchronousManager 中，server在发送model和servertime时，是否应该对servertime加上[] ?


pack.append_tensor_list([
    model_parameters,
    torch.Tensor([self._handler.server_time])
])


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Dun ***@***.***>
发送时间: 2022年4月10日 16:11
收件人: ***@***.***>
抄送: hell ***@***.***>; ***@***.***>
主题: Re: [SMILELab-FL/FedLab-benchmarks] 运行fedasync/cross_process demo出错 (Issue #29)


感谢bug反馈，欢迎一起改进FedLab。

―
