### ISSUE TITLE
异步多线程中 model_time 传输是否有问题？

### ISSUE THREAD

**Issue by kid1999** [SMILELab-FL/FedLab-benchmarks#31]
server manager 传输的 `torch.Tensor(self._handler.server_time)` 
client 回传时直接使用`self.model_time + 1` 
然后server再次拿到model_time进行聚合的时候，`staleness = self.current_time - receive_model_time`

最后导致传输的model_time tensor持续变大！
`2022-04-14 05:34:07,112 - server - INFO - model time : tensor([-1.1402e+13,  1.0000e+00,  1.0000e+00,  1.0000e+00])
2022-04-14 05:34:07,112 - server - INFO - staleness : tensor([1.1402e+13, 4.0000e+00, 4.0000e+00, 4.0000e+00])
`

**Comment by Zengdun-cs** [comment]
抱歉，之前一直没看到，所以没回复。
可能是存在这个问题的，异步目前这边做的测试比较少。
欢迎参与改进。

**Comment by Zengdun-cs** [comment]
近期fedlab基础代码会做一个大的更新，接口和架构会有一些改变和优化，感谢关注。
