### ISSUE TITLE
请问FedAvg的Scale代码使用时是否需要改动？

### ISSUE THREAD

**Issue by rebear077** [SMILELab-FL/FedLab-benchmarks#32]
<img width="912" alt="截图_20224316124327" src="https://user-images.githubusercontent.com/51772538/163661780-e07d1863-293e-47b0-adcd-a7e809f3f2d4.png">
args参数出现问题，请问如何修改？谢谢

**Comment by kid1999** [comment]
应该可以将args换个位置，放到`global_round=5`之前就能解决问题。

**Comment by Zengdun-cs** [comment]
是的，这是个语法错误bug，默认参数位置出错了，之前应该是有默认args的，可能更新丢失了。按楼上说的，把args放到前面，或者手动给一个默认参数就可以了。
