### ISSUE TITLE
请问perfedavg的代码是否能用来跑reddit数据集？

### ISSUE THREAD

**Issue by L-ien** [SMILELab-FL/FedLab-benchmarks#40]
新手想尝试一下联邦学习个性化方向，求教

**Comment by AgentDS** [comment]
你好，你可以试一下，需要改数据读取和数据划分策略。论文原文的数据划分不一定跟我们的一样

**Comment by L-ien** [comment]
请问base model是指models.py中的EmnistCNN吗？可以请教一下修改的方向吗？刚刚接触该领域能力尚有不足，感谢解答！

**Comment by AgentDS** [comment]
是的，这个代码里的EMNISTCNN对reddit不一定能直接用，你可以参考其他代码库里用了reddit数据集的算法用了什么模型，包括数据预处理的transform是怎么样的。
