### ISSUE TITLE
[Fedasync] Executing error

### ISSUE THREAD

**Issue by ysrese** [SMILELab-FL/FedLab-benchmarks#41]
I got this error when executing `FedLab-benchmarks/fedlab_benchmarks/fedasync/standalone/standalone.py` with fedlab==1.1.2.
```
Traceback (most recent call last):
  File "standalone.py", line 300, in <module>
    params_list = trainer.train(model_parameters=model_parameters,
  File "/home/xuan/.local/lib/python3.8/site-packages/fedlab/core/client/scale/trainer.py", line 77, in train
    self._LOGGER.info(
AttributeError: 'NoneType' object has no attribute 'info'
```
Am I missing anything?
Furthermore, which version of fedlab should I used in fedlab_benchmark?

**Comment by Zengdun-cs** [comment]
Fedasync is not updated (currently is fedlab-v1.1.2).  
This is a bug (something are missed). You could fix it by passing a logging object at line 272.

```
from fedlab.utils.logger import Logger 
trainer = AsyncSerialTrainer(
    model=local_model,
    dataset=trainset,
    data_slices=data_indices,
    aggregator=aggregator,
    args=args_test,
    logger=Logger()
)
```

**Comment by ysrese** [comment]
@Zengdun-cs Will you update the new version of FedAsync recently?
