### ISSUE TITLE
celeba处理数据找不到图片

### ISSUE THREAD

**Issue by wanonymous** [SMILELab-FL/FedLab-benchmarks#45]
在使用celeba数据集时，preprocess后 bash gen_pickle_dataset.sh "celeba" "../datasets" "./pickle_datasets"时会报错
FileNotFoundError: [Errno 2] No such file or directory: '/home/fedlab/leaf/datasets/celeba/data/raw/img_align_celeba/162887.jpg'，重新下载数据集或者重新处理，错误仍存在，请问是自己代码的问题吗

**Comment by Zengdun-cs** [comment]
fedlab-benchmarks已停止维护，现在已经集成到了[主库](https://github.com/SMILELab-FL/FedLab/tree/master/datasets)里。

celeba需要先去官网下载数据集，然后按照leaf的要求预处理数据，再调用gen_pickle_dataset。

我最近也在用celeba数据集，没有任何问题。不确定你遇到什么问题，可以试试主库那边的代码。

**Comment by wanonymous** [comment]
> fedlab-benchmarks已停止维护，现在已经集成到了[主库](https://github.com/SMILELab-FL/FedLab/tree/master/datasets)里。
> 
> celeba需要先去官网下载数据集，然后按照leaf的要求预处理数据，再调用gen_pickle_dataset。
> 
> 我最近也在用celeba数据集，没有任何问题。不确定你遇到什么问题，可以试试主库那边的代码。

感谢，是按照要求步骤处理的数据，之前也使用过femnist，是暂时没有找到celeba的报错原因在哪里。Thanks！
![image](https://user-images.githubusercontent.com/44428488/218320342-067e5a8c-1f00-487a-9973-06eeca0270ed.png)

**Comment by Zengdun-cs** [comment]
按你的报错信息来看是数据不全。
可以在主库的脚本里重新试下。
